// <auto-generated />
using Aula_3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aula_3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250326173902_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aula_3.Models.Maquina", b =>
                {
                    b.Property<int>("IdMaquina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_maquina");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMaquina"));

                    b.Property<int>("FkUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("fk_usuario");

                    b.Property<int>("HardDisk")
                        .HasColumnType("integer")
                        .HasColumnName("hard_disk");

                    b.Property<int>("MemoriaRam")
                        .HasColumnType("integer")
                        .HasColumnName("memoria_ram");

                    b.Property<int>("PlacaRede")
                        .HasColumnType("integer")
                        .HasColumnName("placa_rede");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<int>("Velocidade")
                        .HasColumnType("integer")
                        .HasColumnName("velocidade");

                    b.HasKey("IdMaquina");

                    b.HasIndex("FkUsuario");

                    b.ToTable("maquina");
                });

            modelBuilder.Entity("Aula_3.Models.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FkMaquina")
                        .HasColumnType("integer")
                        .HasColumnName("fk_maquina");

                    b.Property<int>("HardDisk")
                        .HasColumnType("integer")
                        .HasColumnName("hard_disk");

                    b.Property<int>("MemoriaRam")
                        .HasColumnType("integer")
                        .HasColumnName("memoria_ram");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("produto");

                    b.HasKey("Id");

                    b.HasIndex("FkMaquina");

                    b.ToTable("software");
                });

            modelBuilder.Entity("Aula_3.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("especialidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Ramal")
                        .HasColumnType("integer")
                        .HasColumnName("ramal");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Aula_3.Models.Maquina", b =>
                {
                    b.HasOne("Aula_3.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("FkUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Aula_3.Models.Software", b =>
                {
                    b.HasOne("Aula_3.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("FkMaquina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquina");
                });
#pragma warning restore 612, 618
        }
    }
}
